services:
  advogados_api:
    build: .
    image: advogados_api
    ports:
      - "3333:3333"
    expose:
      - "3333"
    depends_on:
      - mysql_db
    environment:
      ENV: development
      PORT: 3333
      SECRET_KEY: 4O,Hefe%U_M9kRuu&@dxGrG+pwReQse
      FRONTEND_URL: "http://localhost:3000"

      DB_USER: "test"
      DB_PASSWORD: "test"
      DB_DATABASE: "advogados-template"
      DB_HOST: "mysql_db"
      DB_PORT: "3306"
      ACCESS_TOKEN_EXPIRATION: 86400
    networks:
      - backend

  mysql_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: advogados-template
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3307:3306"
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/docker/volumes/mysql_data
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
    driver: bridge